type Category {
    id: ID!
    name: String!
    description: String
    products: [Product!]!
}

type CategoryOperations {
    allCategories: [Category!]!
    categoryById(id: ID!): Category!
    addCategory(name: String!, description: String): Category!
    updateCategory(id: ID!, name: String, description: String): Category!
    deleteCategory(id: ID!): Boolean!
}

type Product {
    id: ID!
    name: String!
    price: Float!
    stock: Int!
    category: Category!
}

type ProductOperations {
    allProducts: [Product!]!
    productById(id: ID!): Product!
    addProduct(name: String!, price: Float!, stock: Int!, categoryId: ID!): Product!
    updateProduct(id: ID!, name: String, price: Float, stock: Int, categoryId: ID): Product!
    deleteProduct(id: ID!): Boolean!
}

type Query {
    category: CategoryOperations!
    product: ProductOperations!
}

type Mutation {
    category: CategoryOperations!
    product: ProductOperations!
}